// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtkytarsftrlfvzuuidr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0a3l0YXJzZnRybGZ2enV1aWRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NTU0MjksImV4cCI6MjA3MDQzMTQyOX0.jRCtmCbfxJ7cRgWkqgcYnlR6PrUenDRWIlQerx8cPW0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});